// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJmLmQFZlor_l-7qgVnmWProPMjaO_TB8',
    appId: '1:327696741252:web:d6d0bc666a8e22051fa3d1',
    messagingSenderId: '327696741252',
    projectId: 'kpss-ags-son',
    authDomain: 'kpss-ags-son.firebaseapp.com',
    storageBucket: 'kpss-ags-son.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0hLh6V-6eYTzMr7Goi4IBe2CjNTB5Jd8',
    appId: '1:327696741252:android:10e35c1458e9d7111fa3d1',
    messagingSenderId: '327696741252',
    projectId: 'kpss-ags-son',
    storageBucket: 'kpss-ags-son.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj1x-89G1OXtWcpgziIAyTsnKjibpgd6g',
    appId: '1:327696741252:ios:1fe26acaeb4d2b141fa3d1',
    messagingSenderId: '327696741252',
    projectId: 'kpss-ags-son',
    storageBucket: 'kpss-ags-son.firebasestorage.app',
    iosBundleId: 'com.example.kpssAgs2026',
  );
}
